name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: 'build'
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [debug, release]
    steps:
      - uses: actions/checkout@v3
      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'fbc868ee5e12e3e81f464104be246ec06553c274'
          vcpkgJsonGlob: 'vcpkg.json'
      - name: build with cmake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'build-ci'
          buildPresetAdditionalArgs: "['--config ${{matrix.build_type}}']"
          testPreset: 'test-ci'
          testPresetAdditionalArgs: "['--config ${{matrix.build_type}}']"
          configurePreset: 'conf-ci'
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake']"
