name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    container: ghcr.io/skaginn3x/skaginn3x/framework/tfc-toolchain:sha-f8ab815

    steps:
      - uses: actions/checkout@v3
      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'fbc868ee5e12e3e81f464104be246ec06553c274'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: build with cmake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'build-ci'
          testPreset: 'test-ci'
          configurePreset: 'conf-ci'
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake']"
