name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    container: ghcr.io/skaginn3x/skaginn3x/framework/tfc-toolchain:ohg-gcc-test
    strategy:
      fail-fast: false
      matrix:
        compiler: ['gcc', 'clang']
    steps:
      - uses: actions/checkout@v3
      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '213c01f8719e0f8bd48ec6285074a22a7fe5e5a3'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: build with cmake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'build-${{ matrix.compiler }}'
          testPreset: 'test-${{ matrix.compiler }}'
          configurePreset: 'conf-${{ matrix.compiler }}'
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake']"
